In [1]:
import pandas as pd

In [8]:
# import pandas as pd

# Read CSV file
data = pd.read_csv(r"C:\Users\pranj\Downloads\data\data\sales.csv")

# Show first 5 rows
# print(data.head())

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       object
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      object
dtypes: float64(4), int64(5), object(5)
memory usage: 1.3+ GB

In [9]:
data.describe()

,Store,Brand,SalesQuantity,SalesDollars,SalesPrice,Volume,Classification,ExciseTax,VendorNo
count,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07,1.282536e+07
mean,4.389572e+01,1.215460e+04,2.566623e+00,3.524758e+01,1.569027e+01,9.394389e+02,1.413892e+00,1.479431e+00,7.125907e+03
std,2.353947e+01,1.236843e+04,4.551810e+00,8.835689e+01,1.512728e+01,6.993202e+02,4.925295e-01,4.736633e+00,8.742565e+03
min,1.000000e+00,5.800000e+01,1.000000e+00,0.000000e+00,0.000000e+00,5.000000e+01,1.000000e+00,1.000000e-02,2.000000e+00
25%,2.300000e+01,3.663000e+03,1.000000e+00,1.099000e+01,8.990000e+00,7.500000e+02,1.000000e+00,2.100000e-01,3.252000e+03
50%,4.700000e+01,6.349000e+03,1.000000e+00,1.899000e+01,1.299000e+01,7.500000e+02,1.000000e+00,7.500000e-01,4.692000e+03
75%,6.600000e+01,1.795400e+04,2.000000e+00,3.499000e+01,1.899000e+01,1.000000e+03,2.000000e+00,1.570000e+00,9.552000e+03
max,8.100000e+01,9.063100e+04,1.231000e+03,2.606114e+04,5.799990e+03,2.000000e+04,2.000000e+00,1.260520e+03,2.013590e+05

In [11]:
data.to_csv('sales.csv',index=False)

In [7]:
print(data)

                  InventoryId  Store  Brand                 Description  \
0         1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
1         1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
2         1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
3         1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses
4         1_HARDERSFIELD_1005      1   1005     Maker's Mark Combo Pack
...                       ...    ...    ...                         ...
12825358      9_BLACKPOOL_984      9    984      Patron XO Cafe Liqueur
12825359      9_BLACKPOOL_984      9    984      Patron XO Cafe Liqueur
12825360      9_BLACKPOOL_984      9    984      Patron XO Cafe Liqueur
12825361      9_BLACKPOOL_984      9    984      Patron XO Cafe Liqueur
12825362      9_BLACKPOOL_984      9    984      Patron XO Cafe Liqueur

                Size  SalesQuantity  SalesDollars  SalesPrice   SalesDate  \
0              750mL              1         16.49       16.49  2024-01-01
1              750mL              2         32.98       16.49  2024-01-02
2              750mL              1         16.49       16.49  2024-01-03
3              750mL              1         14.49       14.49  2024-01-08
4         375mL 2 Pk              2         69.98       34.99  2024-01-09
...              ...            ...           ...         ...         ...
12825358       750mL              1         25.99       25.99  2024-12-17
12825359       750mL              1         25.99       25.99  2024-12-21
12825360       750mL              3         77.97       25.99  2024-12-23
12825361       750mL              1         25.99       25.99  2024-12-24
12825362       750mL              2         51.98       25.99  2024-12-29

          Volume  Classification  ExciseTax  VendorNo  \
0          750.0               1       0.79     12546
1          750.0               1       1.57     12546
2          750.0               1       0.79     12546
3          750.0               1       0.79     12546
4          375.0               1       0.79     12546
...          ...             ...        ...       ...
12825358   750.0               1       0.79      9165
12825359   750.0               1       0.79      9165
12825360   750.0               1       2.36      9165
12825361   750.0               1       0.79      9165
12825362   750.0               1       1.57      9165

                           VendorName
0         JIM BEAM BRANDS COMPANY
1         JIM BEAM BRANDS COMPANY
2         JIM BEAM BRANDS COMPANY
3         JIM BEAM BRANDS COMPANY
4         JIM BEAM BRANDS COMPANY
...                               ...
12825358  ULTRA BEVERAGE COMPANY LLP
12825359  ULTRA BEVERAGE COMPANY LLP
12825360  ULTRA BEVERAGE COMPANY LLP
12825361  ULTRA BEVERAGE COMPANY LLP
12825362  ULTRA BEVERAGE COMPANY LLP

[12825363 rows x 14 columns]

In [4]:
data

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12825358,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-17,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825359,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-21,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825360,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,3,77.97,25.99,2024-12-23,750.0,1,2.36,9165,ULTRA BEVERAGE COMPANY LLP
12825361,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-24,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825362,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,2,51.98,25.99,2024-12-29,750.0,1,1.57,9165,ULTRA BEVERAGE COMPANY LLP

In [8]:
data.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [26]:
# data = pd.read_csv("sales.csv")

In [ ]:
data.to_csv("sales.csv",index=False)

In [4]:
import os 
print(os.listdir())

['.ipynb_checkpoints', 'sales.csv', 'Untitled.ipynb']

In [27]:
print(data.shape)

(5543, 10)

In [28]:
data.sample(5)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
953,7154,PREMIER DISTRIBUTORS,2024-03-12,9092,2024-02-25,2024-04-13,125,1909.36,10.12,NaN
1024,90011,FORTUNE WINE BROKERS LLC,2024-03-21,9137,2024-02-29,2024-04-25,34,246.92,1.33,NaN
1953,6359,OLE SMOKY DISTILLERY LLC,2024-05-23,10045,2024-05-02,2024-06-16,112,1035.37,5.07,NaN
1914,1485,CASTLE BRANDS CORP.,2024-05-17,10081,2024-05-05,2024-06-18,1725,26578.90,127.58,NaN
2526,1485,CASTLE BRANDS CORP.,2024-07-05,10715,2024-06-17,2024-08-06,1766,27531.69,129.40,NaN

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv(r"C:\Users\pranj\Downloads\data\data\begin_inventory.csv")

In [5]:
data.head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

In [18]:
data.to_csv("begin_inventory.csv", index=False)

In [19]:
import os 
print(os.listdir())

['.ipynb_checkpoints', 'begin_inventory.csv', 'end_inventory.csv', 'sales.csv', 'Untitled.ipynb']

In [20]:
print(data.shape)

(206529, 9)

In [21]:
data.sample(4)

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
33574,14_BROMWICH_21320,14,BROMWICH,21320,Zion Dolev Muscato,750mL,10,10.99,2024-01-01
142992,59_CLAETHORPES_22079,59,CLAETHORPES,22079,C Y Toro Casa Diblo Cab Svgn,750mL,44,9.99,2024-01-01
198265,76_DONCASTER_23948,76,DONCASTER,23948,Ch La Croix Lartigue 09,750mL,37,38.99,2024-01-01
88490,37_PAETHSMOUTH_6498,37,PAETHSMOUTH,6498,Franzia Chablis Old World C,5L,8,16.99,2024-01-01

In [23]:
import os 
print(os.getcwd())

C:\Users\pranj\Data

In [24]:
print(data)

               InventoryId  Store          City  Brand  \
0        1_HARDERSFIELD_58      1  HARDERSFIELD     58
1        1_HARDERSFIELD_60      1  HARDERSFIELD     60
2        1_HARDERSFIELD_62      1  HARDERSFIELD     62
3        1_HARDERSFIELD_63      1  HARDERSFIELD     63
4        1_HARDERSFIELD_72      1  HARDERSFIELD     72
...                    ...    ...           ...    ...
206524  79_BALLYMENA_46985     79     BALLYMENA  46985
206525  79_BALLYMENA_47014     79     BALLYMENA  47014
206526  79_BALLYMENA_47090     79     BALLYMENA  47090
206527  79_BALLYMENA_90011     79     BALLYMENA  90011
206528  79_BALLYMENA_90089     79     BALLYMENA  90089

                         Description   Size  onHand   Price   startDate
0        Gekkeikan Black & Gold Sake  750mL       8   12.99  2024-01-01
1             Canadian Club 1858 VAP  750mL       7   10.99  2024-01-01
2           Herradura Silver Tequila  750mL       6   36.99  2024-01-01
3         Herradura Reposado Tequila  750mL       3   38.99  2024-01-01
4               No. 3 London Dry Gin  750mL       6   34.99  2024-01-01
...                              ...    ...     ...     ...         ...
206524  Rodney Strong Cab Svgn Alexa  750mL      13   22.99  2024-01-01
206525           Juan Gil Jumilla Rd  750mL      13   13.99  2024-01-01
206526    Napa Cellars Cab Svgn Napa  750mL      19   23.99  2024-01-01
206527  Ch Pichon Longville 12 Pauil  750mL      12  144.99  2024-01-01
206528    Ch Lynch Bages 12 Pauillac  750mL      24  119.99  2024-01-01

[206529 rows x 9 columns]

In [7]:
data

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01
...,...,...,...,...,...,...,...,...,...
206524,79_BALLYMENA_46985,79,BALLYMENA,46985,Rodney Strong Cab Svgn Alexa,750mL,13,22.99,2024-01-01
206525,79_BALLYMENA_47014,79,BALLYMENA,47014,Juan Gil Jumilla Rd,750mL,13,13.99,2024-01-01
206526,79_BALLYMENA_47090,79,BALLYMENA,47090,Napa Cellars Cab Svgn Napa,750mL,19,23.99,2024-01-01
206527,79_BALLYMENA_90011,79,BALLYMENA,90011,Ch Pichon Longville 12 Pauil,750mL,12,144.99,2024-01-01
206528,79_BALLYMENA_90089,79,BALLYMENA,90089,Ch Lynch Bages 12 Pauillac,750mL,24,119.99,2024-01-01

In [8]:
import pandas as pd

In [9]:
data =pd.read_csv(r"C:\Users\pranj\Downloads\data\data\purchase_prices.csv")

In [10]:
data.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [11]:
data.to_csv("purchase_prices.csv",index = False)

In [15]:
import os 
print(os.listdir())

['.ipynb_checkpoints', 'begin_inventory.csv', 'end_inventory.csv', 'purchases.csv', 'purchase_prices.csv', 'sales.csv', 'Untitled.ipynb']

In [13]:
data = pd.read_csv(r"C:\Users\pranj\Downloads\data\data\purchases.csv")

In [14]:
data.to_csv("purchases.csv",index= False)

In [16]:
import pandas as pd # pandas import step 1

In [17]:
data = pd.read_csv(r"C:\Users\pranj\Downloads\data\data\vendor_invoice.csv")  #read file

In [18]:
data.to_csv("vendor_invoice.csv", index = False)  #load file

In [20]:
data.head()   # show data

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN

In [19]:
import os   # list of file name in folder
print(os.listdir())

['.ipynb_checkpoints', 'begin_inventory.csv', 'end_inventory.csv', 'purchases.csv', 'purchase_prices.csv', 'sales.csv', 'Untitled.ipynb', 'vendor_invoice.csv']

In [22]:
print(data.shape)  # show the file in row and cloum values

(5543, 10)

In [23]:
data   # all data shows

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,NaN
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,NaN
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,NaN
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,NaN
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,NaN

In [24]:
data.sample(2)   #shows 2 line random data

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
5454,2242,DELICATO VINEYARDS INC,2025-01-10,13554,2024-12-18,2025-02-03,5210,45684.82,237.56,NaN
447,7255,PSP WINES,2024-02-05,8541,2024-01-19,2024-03-06,416,3247.06,17.21,NaN

In [25]:
data.head(2) #first 2 line shows

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN

In [17]:
import pandas as pd 
import os 
from sqlalchemy import create_engine

In [18]:
engine = create_engine("sqlite:///inventory.db")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [19]:
import os 
print(os.getcwd())

C:\Users\pranj\Data

In [20]:
import os 
print(os.listdir())

['.ipynb_checkpoints', 'begin_inventory.csv', 'end_inventory.csv', 'Exploratory data analysis.ipynb', 'get_vendor_summary.py', 'ingestion_db.py', 'inventory.db', 'logs', 'purchases.csv', 'purchase_prices.csv', 'sales.csv', 'Untitled.ipynb', 'vendor_invoice.csv', '__pycache__']

In [24]:
import os
os.getcwd()

'C:\\Users\\pranj\\Data'

In [9]:
print (os.listdir())

['.ipynb_checkpoints', 'begin_inventory.csv', 'end_inventory.csv', 'Exploratory data analysis.ipynb', 'get_vendor_summary.py', 'ingestion_db.py', 'inventory.db', 'logs', 'purchases.csv', 'purchase_prices.csv', 'sales.csv', 'Untitled.ipynb', 'vendor_invoice.csv', '__pycache__']

In [25]:
folder = "C:\Users\pranj\Downloads\data\data"

# r"C:\\Users\\pranj\\Data"

In [26]:
for file in os.listdir(folder):
    if file.endswith('.csv'):
        path = os.path.join(folder, file)
        df = pd.read_csv(path)
        print(file, df.shape)
        ingest_db(df,file[:-4], engine)

begin_inventory.csv (206529, 9)
end_inventory.csv (224489, 9)
purchases.csv (2372474, 16)
purchase_prices.csv (12261, 9)
sales.csv (12825363, 14)
vendor_invoice.csv (5543, 11)

In [12]:
def ingest_db(df, table_name, engine):
    df.to_sql(table_name, con = engine, if_exists = 'replace', index = False)

In [27]:
# Scipt
import pandas as pd 
import os 
from sqlalchemy import create_engine
import logging
import time

logging.basicConfig(
    filename = "logs/ingestion_db.log",
    level = logging.DEBUG,
    format = "%(asctime)s - %(levelname)s - %(message)s",
    filemode = "a"
)

In [28]:
def load_raw_data(folder):
    ''' this function is load the csv as dataframe and ingest into db'''
    start = time.time()
    for file in os.listdir(folder):
        if file.endswith('.csv'):
           path = os.path.join(folder, file)
           df = pd.read_csv(path)
           logging.info(f'ingesting {file} in db')
           ingest_db(df,file[:-4], engine)
         
        end = time.time()
        total_time = (end - start)/60
        logging.info('-------ingestion complete---------')
        
        logging.info(f'total time taken:{total_time} minutes')

In [15]:
def ingest_db(df, table_name, engine):
    ''' this function will ingest dataframe into database table'''
    df.to_sql(table_name, con = engine, if_exists = 'replace', index = False)

In [5]:
import pandas as pd 
import os 
from sqlalchemy import create_engine
import logging
import time

logging.basicConfig(
    filename = "logs/ingestion_db.log",
    level = logging.DEBUG,
    format = "%(asctime)s - %(levelname)s - %(message)s",
    filemode = "a"
)

engine = create_engine("sqlite:///inventory.db")
def ingest_db(df, table_name, engine):
    ''' this function will ingest dataframe into database table'''
    df.to_sql(table_name, con = engine, if_exists = 'replace', index = False)

def load_raw_data(folder):
    ''' this function is load the csv as dataframe and ingest into db'''
    start = time.time()
    for file in os.listdir(folder):
        if file.endswith('.csv'):
           path = os.path.join(folder, file)
           df = pd.read_csv(path)
           logging.info(f'ingesting {file} in db')
           ingest_db(df,file[:-4], engine)
         
    end = time.time()
    total_time = (end - start)/60
    logging.info('-------ingestion complete---------')
        
    logging.info(f'total time taken:{total_time} minutes')

if __name__ == "__main__":
    folder = r"C:\Users\pranj\Downloads\data\data" 
    load_raw_data(folder)

In [6]:
import os
print(os.path.exists(folder))

True

In [7]:
import os

folder = r"C:\Users\pranj\Downloads\data\data" 

print(os.path.exists(folder))

True